FileProcessor Class Reference
Public Member Functions
FileProcessor ()
List< File > ReadFiles (String filePath)
List< File > ReadFile (String[] filePaths)
List< File > ReadFilesAlternative (String[] filePaths)
Detailed Description
Class for processing files. It extracts text out of the files using ApacheTika, Tesseract, or GroupDocs and stores the relevant data in File objects.
Constructor & Destructor Documentation
FileProcessor()
FileProcessor.FileProcessor ()
Creates a FileProcessor object.
Member Function Documentation
ReadFile()
List< File > FileProcessor.ReadFile (String[] filePaths)
Returns file that can be put into Elasticsearch. It extracts text from the given file with the appropriate tool (Tesseract for files with .jpg extension and ApacheTika for everything else), and stores the data in a File object.
Parameters
filePath The file path of the file that is being processed.
Returns
Returns a single File object storing the relevant data for a single file.
References FileID.newId().
ReadFiles()
List< File > FileProcessor.ReadFiles (String filePath)
Returns list of files that can be put into Elasticsearch. For each file in the given directory, it extracts text from the file with the appropriate tool (Tesseract for files with .jpg extension and ApacheTika for everything else), and stores the data in a File object, and adds that file object to the output list.
Parameters
filePath The filepath of the directory that is being processed.
Returns
Returns a list of File objects, each storing the relevant data for a single file in the given directory.
References FileID.newId().
ReadFilesAlternative()
List< File > FileProcessor.ReadFilesAlternative (String[] filePaths)
Reads the files using GroupDocs and returns a list of the resulting File objects. For each given file path, it extracts the text using the GroupDocs tool, creates a file object to store the data, and adds it to the output list.
Parameters
filePaths An array of file paths to be processed.
Returns
Returns a List of file objects, where each file object stores the data of a single file.
References FileID.newId().
The documentation for this class was generated from the following file:
FileProcessor.cs