FileID Class Reference
Static Public Member Functions
static int newId ()
Detailed Description
A small utility class that generates identifiers for file objects.
Member Function Documentation
newId()
static int FileID.newId () [static]
Increments ID ensuring a unique ID for each file that has been processed.
Returns
Returns a unique ID.
Referenced by FileProcessor.ReadFile(), FileProcessor.ReadFiles(), and FileProcessor.ReadFilesAlternative().
The documentation for this class was generated from the following file:
FileID.cs