ElasticAccess Class Reference
Public Member Functions
ElasticAccess ()
ElasticClient Client ()
void IndexDocument (File file)
void IndexDocuments (List< File > files)
List< File > SearchAll ()
List< File > SearchByName (string fileName)
List< File > SearchByText (string text)
List< File > SearchByAddress (string text)
List< File > SearchByPhone (string text)
List< File > SearchByEmail (string text)
void DeleteAll ()
Detailed Description
Manages the connection with ElasticSearch. Performs all operations that are related to ElasticSearch including indexing files and performing queries to find files in Elasticsearch that satisfy a condition.
Constructor & Destructor Documentation
ElasticAccess()
ElasticAccess.ElasticAccess ()
Creates an ElasticAccess object.
References Client().
Member Function Documentation
Client()
ElasticClient ElasticAccess.Client ()
Creates Elasticsearch client.
Returns
Returns the new Elasticsearch client.
Referenced by ElasticAccess().
DeleteAll()
void ElasticAccess.DeleteAll ()
Deletes all files currently in Elasticsearch.
IndexDocument()
void ElasticAccess.IndexDocument (File file)
Indexes a single file into Elasticsearch.
Parameters
file The file to be indexed.
IndexDocuments()
void ElasticAccess.IndexDocuments (List< File > files)
Indexes a list of files into Elasticsearch.
Parameters
files A list of files to be indexed.
SearchAll()
List< File > ElasticAccess.SearchAll ()
Returns the first 100 files currently in Elasticsearch.
Returns
Returns a list of the first 100 files in Elasticsearch.
Referenced by MainWindow.MainWindow().
SearchByAddress()
List< File > ElasticAccess.SearchByAddress (string text)
Finds the files in Elasticsearch that contain the given US postal address.
Parameters
text An address to search for.
Returns
Returns the list of first 100 files currently in Elasticsearch that contain the given address.
SearchByEmail()
List< File > ElasticAccess.SearchByEmail (string text)
Finds the files in Elasticsearch that contain the given email address.
Parameters
text An email address to search for.
Returns
Returns the list of first 100 files currently in Elasticsearch that contain the given address
SearchByName()
List< File > ElasticAccess.SearchByName (string fileName)
Finds the files in Elasticsearch that have the given file name.
Parameters
fileName The name of a file to search for.
Returns
Returns list of first 100 files currently in Elasticsearch whose file names contain the given file name.
SearchByPhone()
List< File > ElasticAccess.SearchByPhone (string text)
Finds the files in Elasticsearch that contain the given phone number.
Parameters
text A phone number to search for.
Returns
Returns the list of first 100 files currently in Elasticsearch that contain the given address.
SearchByText()
List< File > ElasticAccess.SearchByText (string text)
Finds the files in Elasticsearch that contain the given substring in their text.
Parameters
text A substring to search for.
Returns
Returns the list of first 100 files currently in Elasticsearch that contain the given text.
The documentation for this class was generated from the following file:
ElasticAccess.cs